build.gradle.kts
src/main/kotlin/com/yapp/web2/domain/BaseTimeEntity.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Urls.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/repository/FolderRepository.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/domain/notification/controller/NotificationController.kt
src/main/kotlin/com/yapp/web2/domain/notification/entity/NotifIcation.kt
src/main/kotlin/com/yapp/web2/domain/notification/entity/Notifaction.kt
src/main/kotlin/com/yapp/web2/domain/notification/repository/NotificationRepository.kt
src/main/kotlin/com/yapp/web2/domain/notification/service/NotificationService.kt
src/main/kotlin/com/yapp/web2/domain/user/controller/UserController.kt
src/main/kotlin/com/yapp/web2/domain/user/entity/Account.kt
src/main/kotlin/com/yapp/web2/domain/user/repository/UserRepository.kt
src/main/kotlin/com/yapp/web2/domain/user/service/UserService.kt
src/main/kotlin/com/yapp/web2/exception/ErrorResponse.kt

- Controller
- Service
- Entity
- Repository

[#4] feat(초기화): 초기 프로젝트 셋팅

---

src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/repository/FolderRepository.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/domain/notification/entity/Notification.kt
src/main/kotlin/com/yapp/web2/domain/user/entity/Account.kt
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt

[#9] feat(폴더 API)

---

src/main/kotlin/com/yapp/web2/domain/bookmark/controller/TrashController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkServiceTest.kt

[#15] feat(휴지통 API)

---

src/main/kotlin/com/yapp/web2/domain/account/controller/UserController.kt
src/main/kotlin/com/yapp/web2/domain/account/entity/Account.kt
src/main/kotlin/com/yapp/web2/domain/account/repository/UserRepository.kt
src/main/kotlin/com/yapp/web2/domain/account/service/UserService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/AccountFolder.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/repository/FolderRepository.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/domain/notification/entity/Notification.kt
src/main/kotlin/com/yapp/web2/security/jwt/JwtProvider.kt
src/main/kotlin/com/yapp/web2/security/jwt/TokenAuthenticationFilter.kt
src/main/resources/data.sql
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt

- 폴더 조회 API 로직 수정
- Access-Token 추가
- 리팩토링

[#9] refactor(폴더)

---

src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkPageService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/repository/FolderRepository.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/exception/GlobalExceptionHandler.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkServiceTest.kt
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt

- 폴더 조회 API(findAll)
- Request Valid

[#25] fix(폴더 조회 API)

---

build.gradle.kts
src/main/kotlin/com/yapp/web2/config/SecurityConfig.kt
src/main/kotlin/com/yapp/web2/config/SwaggerConfig.kt
src/main/kotlin/com/yapp/web2/domain/account/controller/UserController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/TrashController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/security/jwt/TokenAuthenticationFilter.kt
src/main/kotlin/com/yapp/web2/security/jwt/TokenDto.kt

- Security Config
- Folder
- Bookmark
- Token
- Trash
- User(Account)

[#17] feat(Swagger 설정)

---

src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/repository/FolderRepository.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/exception/ErrorResponse.kt
src/main/kotlin/com/yapp/web2/exception/GlobalExceptionHandler.kt
src/main/resources/data.sql

[#9] refactor(폴더 삭제)

---

src/main/kotlin/com/yapp/web2/domain/account/controller/AccountController.kt
src/main/kotlin/com/yapp/web2/domain/account/entity/Account.kt
src/main/kotlin/com/yapp/web2/domain/account/repository/AccountRepository.kt
src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt
src/main/kotlin/com/yapp/web2/exception/GlobalExceptionHandler.kt
src/main/kotlin/com/yapp/web2/exception/custom/AccountException.kt
src/main/kotlin/com/yapp/web2/util/Message.kt
src/test/kotlin/com/yapp/web2/domain/account/service/AccountServiceTest.kt

Feature/#14 로그인&회원가입api

---

src/main/kotlin/com/yapp/web2/domain/notification/controller/NotificationController.kt
src/main/kotlin/com/yapp/web2/domain/notification/entity/dto/RemindCycleRequest.kt
src/main/kotlin/com/yapp/web2/domain/notification/entity/dto/RemindToggleRequest.kt
src/main/kotlin/com/yapp/web2/domain/notification/service/NotificationService.kt

- remind alarm update(toggle) api
- remind alarm cycle update api
- request dto

[#32] feat(remind)

---

src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/move/inner/FolderMoveWithEqualParentOrTopFolder.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/move/outer/FolderMoveFromFolderToTopFolder.kt

- 폴더 -> 최상위폴더 이동 시 index 설정 추가
- rename

[#32] refacotr(folder move)

---

src/main/kotlin/com/yapp/web2/config/S3Uploader.kt
src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkSearchService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/exception/GlobalExceptionHandler.kt
src/main/kotlin/com/yapp/web2/exception/custom/AccountNotFoundException.kt
src/main/kotlin/com/yapp/web2/exception/custom/BookmarkNotFoundException.kt
src/main/kotlin/com/yapp/web2/exception/custom/FolderNotFoundException.kt
src/main/kotlin/com/yapp/web2/util/ExceptionMessage.kt
src/main/kotlin/com/yapp/web2/util/Message.kt
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt

- TODO: S3 업로드 실패 시 예외 추가
- Custom Exception & Message 추가
- Inline variable(BookmarkSearchService - searchKeywordOwnUserId)
- Method Encapsulation
- Optional ifPresent -> Kotlin let
- Test Code Fail -> Pass
- remove not used import
- remove TODO

[#25] 리팩토링

---

src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt

[#9] feat(단일 폴더이동 by 버튼)

---

build.gradle.kts
src/main/kotlin/com/yapp/web2/batch/job/NotificationConfig.kt
src/main/kotlin/com/yapp/web2/domain/account/entity/Account.kt
src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/domain/notification/repository/NotificationRepository.kt
src/main/kotlin/com/yapp/web2/domain/remind/controller/RemindController.kt
src/main/kotlin/com/yapp/web2/domain/remind/entity/Remind.kt
src/main/kotlin/com/yapp/web2/domain/remind/entity/dto/RemindCycleRequest.kt
src/main/kotlin/com/yapp/web2/domain/remind/entity/dto/RemindToggleRequest.kt
src/main/kotlin/com/yapp/web2/domain/remind/repository/RemindRepository.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt
src/main/kotlin/com/yapp/web2/exception/custom/RemindCycleValidException.kt
src/main/kotlin/com/yapp/web2/util/ExceptionMessage.kt
src/main/kotlin/com/yapp/web2/util/RemindCycleUtil.kt
src/test/kotlin/com/yapp/web2/domain/account/service/AccountServiceTest.kt

- FCM dependenecy 추가
- Notification -> Remind 네이밍 일관성
- Batch 부분은 사이드 이펙트가 있을수도 있어서 변경안했는데, 필요하다면 변경하겠습니다.
- Add Swagger
- 회원가입 시 디폴트 보관함 생성 로직 수정
- 회원 - 폴더 연관관계 설정(AccountFolder)
- remindCycle String -> Int 변경
- remindCycle 유효성 검사 추가(3일, 7일, 14일, 30일)

[#32] refactor & feat(리마인드)

---

src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/remind/controller/RemindController.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt
src/test/kotlin/com/yapp/web2/domain/remind/service/RemindServiceTest.kt

- 알람 설정 OFF(토글) test
- 리마인드 주기 변경 test
- 리마인드 주기 변경 유효성 검사 test
- 리마인드 해제 API 추가
- remindTime = null < 이 로직만 추가했는데 맞을지 확인 한번 부탁드려요~

[#32] 리마인드 해제 API & 리마인드 API 테스트

---

src/main/kotlin/com/yapp/web2/domain/account/controller/AccountController.kt
src/main/kotlin/com/yapp/web2/domain/account/entity/Account.kt
src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt

- profile image upload API 추가
- changeProfile API 추가

[#23] feature(profile)

---

src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkPageService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt

- 북마크를 삭제할 때, 복원된 북마크 중에서 폴더가 존재하지 않는 북마크를 처리하는 로직 추가
- 리마인드 설정할 때, 리마인드 주기 추가
- 리마인드 부분에서 기한이 오늘부터인 remind설정의 북마크를 가져오는 로직 수정

[#10] fix(bookmark)

---

src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt

- 폴더 수정 변경
- 폴더 이모지 수정 + 폴더 이름 수정 통합 -> 폴더 이름 + 이모지 수정

[#9] 폴더 API

---

src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt

- 폴더 삭제 시 해당 폴더 하위에 존재하는 모든 폴더와 모든 북마크 삭제
- 구현 방법이 당장 생각나는게 없어서 재귀로 구현했는데, 다른 좋은 방법이 있으면 조언 부탁드립니다.

[#9] feat(폴더 삭제 API)

---

src/main/kotlin/com/yapp/web2/domain/account/entity/Account.kt

- remove fcmToken in Login Response 
- remove not used import

[#25] fix(Account Login Response)

---

src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/main/kotlin/com/yapp/web2/domain/notification/entity/dto/RemindCycleRequest.kt
src/main/kotlin/com/yapp/web2/domain/remind/controller/RemindController.kt
src/main/kotlin/com/yapp/web2/domain/remind/entity/dto/ReadRemindListRequest.kt
src/main/kotlin/com/yapp/web2/domain/remind/entity/dto/RemindListResponse.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt
src/test/kotlin/com/yapp/web2/domain/remind/service/RemindServiceTest.kt

- 코드 리팩토링
- 리마인드 리스트 조회 API
- Client가 리마인드 확인한 처리 API

[#32] feat(리마인드)

---

src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt

[#25] fix(compile error)

---

src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/main/kotlin/com/yapp/web2/domain/remind/controller/RemindController.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt
src/main/kotlin/com/yapp/web2/util/Message.kt

> 서버에 바로 반영하기 위해 Merge 하겠습니다.
- 리마인드 배치 발송 조회 조건 추가 - remindStatus = false
- 리마인드 리스트 조회 API Response 변경
- 리마인드 title 제목 변경(Message)

[#32] feat(FCM)

---

src/main/kotlin/com/yapp/web2/domain/remind/entity/dto/RemindListResponseWrapper.kt

[#32] feat(FCM): 리마인드 리스트 조회 API Response 

---

src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt

[#32] fix(Remind): 리마인드 리스트 조회 시 발송시각(remindTime)이 NotNull인 조건 추가

---

src/main/kotlin/com/yapp/web2/domain/remind/controller/RemindController.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt

- 테스트를 위한 API입니다. (작업 후 삭제 예정)

[#32] feat(Remind): 리마인드 리스트 조회 테스트를 위한 임시 API

---

src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt
src/main/kotlin/com/yapp/web2/domain/folder/repository/FolderRepository.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt

- 폴더 리팩토링
- 폴더 추가 시 폴더 index 서버에서 관리
- 생성 가능한 폴더 개수 제한 해제
- CRLF -> LF
- Spring Data JPA repository: Using Named Parameters
- 실패하는 테스트코드 fix

[#25] refactor(folder)

---

src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt

폴더에 해당하지 않는 북마크를 추가하는 기능 추가
- controller, service, Bookmark Entity 변경

[#10] feature(bookmark save): 모든 도토리에만 저장되는 북마크 추가 기능 추가

---

src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/test/kotlin/com/yapp/web2/domain/account/service/AccountServiceTest.kt
src/test/kotlin/com/yapp/web2/domain/remind/service/RemindServiceTest.kt

- 테스트 코드 일부 수정하였습니다.
- 몇몇 테스트는 아직 실패해서 추가 작업이 필요합니다.

[#25] refactoring

---

build.gradle.kts
src/main/kotlin/com/yapp/web2/batch/job/JobCompletionListener.kt
src/main/kotlin/com/yapp/web2/batch/job/NotificationJob.kt
src/main/kotlin/com/yapp/web2/batch/scheduler/RemindNotificationScheduler.kt
src/main/kotlin/com/yapp/web2/infra/slack/SlackService.kt
src/main/kotlin/com/yapp/web2/infra/slack/SlackServiceImpl.kt

- Spring Batch - Slack 연동
- JobListener, SlackApi
- Spring Batch 에서 Job 작업 후(리마인드) 실패하는 건에 대해 슬랙 알림 오도록 연동

[#116] Spring Batch - Slack 연동

---

build.gradle.kts

- 중괄호 하나가 누락되어서 추가했습니다. 따로 리뷰 없이 바로 머지 하겠습니다~

[#25] 누락된 중괄호 추가

---

.gitignore

local 환경에서의 docker-compose.yaml과 properties 추가를 위한 ignore 수정
.ignore 수정

[#25]fix(ignore)

---

.github/workflows/gradle.yml

- CI 테스트
- 테스트용이라 작업이 따로 없어서 바로 머지할게요~

[#125] GitHub-Action CI 테스트

---

src/main/kotlin/com/yapp/web2/domain/account/entity/Account.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Remind.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkServiceTest.kt

설계 변경으로 인한, remind 로직을 변경하였습니다.
변경되면서 바뀐 test를 진행하였습니다!
- Remind 클래스 추가
- Bookmark 클래스에 Remind List 추가
- bookmarkUpdate 로직 변경 & toggleOnRemindBookmark & toggleOffRemindBookmark 추가
- bookmarkUpdateTest 추가

[#10] bookmark 설계 변경

---

.github/workflows/github-actions.yml
.github/workflows/gradle.yml
Dockerfile
Dockerfile-dev
Dockerfile-prod

- GitHub Actions CI/CD
- Docker, Docker-Compose, AWS, spring profiles(prod, dev)

[#125] GitHub-Actions CI/CD

---

src/main/kotlin/com/yapp/web2/config/SecurityConfig.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkPageController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/BookmarkDto.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/BookmarkInterface.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/BookmarkUtils.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/PersonalBookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/SharedBookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkInterfaceRepository.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkInterfaceService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkPageService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/AccountFolder.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/util/AES256Util.kt
src/main/kotlin/com/yapp/web2/util/FolderTokenDto.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkInterfaceServiceTest.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkServiceTest.kt
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt
src/test/kotlin/com/yapp/web2/util/AES256UtilTest.kt

공유기능 적용을 위한 accountFolder 수정 및 코드 수정
+ val로 Remind List를 선언하니, 불변객체이기 때문에 나는 오류 수정
- 공유 계정에 따른 accountFolder에 권한속성 추가
- 보관함 folder를 추가할 때, Admin 권한 설정할 수 있도록 변경
- test에서 불필요한 코드 수정(assertEquals -> assertThrow)
- bookmarkList라는 변수명을 좀 더 도토리함스럽게 변경하기 위한 변수명 수정(요청사항)

Feature/#10 북마크api

---

src/main/kotlin/com/yapp/web2/batch/job/NotificationJob.kt
src/main/kotlin/com/yapp/web2/batch/job/TrashRefreshJob.kt
src/main/kotlin/com/yapp/web2/batch/scheduler/TrashRefreshScheduler.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/test/kotlin/com/yapp/web2/batch/BatchTestConfig.kt
src/test/kotlin/com/yapp/web2/batch/job/TrashRefreshJobTest.kt
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderMoveServiceTest.kt

- 휴지통에서 30일이 지난 북마크 삭제 배치
- Spring Batch
- Batch Test
- CRLF -> LF

[#116] 북마크 삭제 배치

---

.github/workflows/github-actions.yml

[#130] chore: script 내 주석 제거

---

build.gradle.kts
src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/test/kotlin/com/yapp/web2/domain/folder/controller/FolderControllerTest.kt
src/test/kotlin/com/yapp/web2/domain/folder/service/FolderServiceTest.kt

[#9] 리팩토링 및 테스트 코드 추가

---

src/main/resources/logback-spring.xml

- docker-compose와 로그 파일 경로 맞춰주도록 수정
- 테스트라서 바로 Merge 하겠습니다!

[#140] log 경로 수정(테스트)

---

.github/workflows/github-actions.yml
src/main/kotlin/com/yapp/web2/exception/ObjectNotFoundException.kt
src/main/kotlin/com/yapp/web2/exception/custom/ObjectNotFoundException.kt
src/main/resources/logback-spring.xml

[#140] logback 설정

---

src/main/kotlin/com/yapp/web2/domain/account/controller/AccountController.kt
src/main/kotlin/com/yapp/web2/domain/account/entity/Account.kt
src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/BookmarkInterface.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/BookmarkUtils.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkPageService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/PersonalBookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/SharedBookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt

[#132] fix : compile error fix

---

.gitignore
src/main/kotlin/com/yapp/web2/config/SecurityConfig.kt
src/main/kotlin/com/yapp/web2/config/SwaggerConfig.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/BookmarkDto.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkInterfaceController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/PersonalBookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkPageService.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkServiceTest.kt

- 북마크 추가 컨트롤러 통일
- 폴더 아이디 암호화 API Authorization 제거
- swagger authorization key 이름 변경
- JWT -> accessToken으로 변경
- bookmarkDto의 AddBookmarkListDto의 list를 mutableList로 변경
- addBookmark Controller 하나로 통일
- 폴더 아이디 암호화 API Authorization 제거
- log file gitignore 추가

북마크 컨트롤러 리펙토링 && Authorization 범위 변경

---

src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkPageService.kt

refactor(bookmarkPageService): 불필요한 import 제거

---

src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt

- 로그인 했을경우 isRegistered 변수 true로 변경

[#140] refactor: 로그인 시 등록 여부 변수 true로 변경

---

src/main/kotlin/com/yapp/web2/domain/folder/controller/FolderController.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt

폴더 이름 조회에서 폴더 id가 아닌, 폴더 token으로 조회할 수 있도록 변경
- folderConroller 변경
- folderService 변경

fix(getFolderName)

---

src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkPageService.kt
src/main/kotlin/com/yapp/web2/domain/folder/entity/Folder.kt

- 일부 버그사항 수정
- 로그인 시 등록 여부 변수 true로 변경
- 폴더 이름 조회에서 폴더 id가 아닌 폴더 token으로 조회할 수 있도록 변경

[#140] 버그 수정

---

.github/workflows/github-actions.yml
src/main/resources/logback-spring.xml

- spring logback 로그파일 경로 수정 
- 테스트용이라 바로 Merge 하겠습니다!

[#140] spring logback 로그파일 경로 수정

---

README.md
src/intTest/kotlin/com/yapp/web2/util/AbstractControllerTest.kt
src/main/kotlin/com/yapp/web2/batch/job/TrashRefreshJob.kt
src/main/kotlin/com/yapp/web2/config/S3Client.kt
src/main/kotlin/com/yapp/web2/domain/account/controller/AccountController.kt
src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/folder/service/FolderService.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt
src/main/kotlin/com/yapp/web2/infra/fcm/FirebaseService.kt
src/main/kotlin/com/yapp/web2/infra/slack/SlackServiceImpl.kt
src/test/kotlin/com/yapp/web2/config/S3ClientTest.kt
src/test/kotlin/com/yapp/web2/domain/account/service/AccountServiceTest.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkServiceTest.kt
src/test/kotlin/com/yapp/web2/util/RandomUtilsTest.kt

- 리팩터링
- README 수정
- 클래스명 수정
- 로깅 추가
- import 와일드카드 제거
- 비즈니스 로직에 파라미터 유효성 검증 추가
- 휴지통에서 30일이 지난 북마크 자동 삭제 로직 수정 및 로깅 추가

[#140] 리팩터링

---

src/main/kotlin/com/yapp/web2/domain/bookmark/BookmarkDto.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/SharedBookmarkServiceTest.kt

[#173] 북마크 추가 버그 fix

---

src/intTest/kotlin/com/yapp/web2/domain/account/controller/AccountControllerTest.kt
src/main/kotlin/com/yapp/web2/batch/job/NotificationJob.kt
src/main/kotlin/com/yapp/web2/config/SecurityConfig.kt
src/main/kotlin/com/yapp/web2/domain/account/controller/AccountController.kt
src/main/kotlin/com/yapp/web2/domain/account/entity/Account.kt
src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/BookmarkDto.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/TrashController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Bookmark.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Remind.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepositoryImpl.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/MongoTemplateRepository.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkPageService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkService.kt
src/main/kotlin/com/yapp/web2/domain/remind/controller/RemindController.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt
src/main/kotlin/com/yapp/web2/util/ExceptionMessage.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepositoryTest.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/BookmarkServiceTest.kt
src/test/kotlin/com/yapp/web2/domain/remind/service/RemindServiceTest.kt

- 리마인드 로직 수정 및 리팩터링
- remind -> MutableList<Remind>로 수정
- Remind 내 userId 값이 존재하므로 대부분 userId 값을 추가하여 사용
- Repository 쿼리 일부 수정 및 Custom Repository 추가
- 변경된 로직 & API
- 리마인드 발송 대상 Bookmark List 조회 로직 수정
- 리마인드 토글 On / Off 설정 로직 수정
- 리마인드가 발송된 북마크 리스트 조회 로직 수정
- 리마인드 읽음처리 로직 수정
- 전반적인 로깅 추가
- Class layout order 수정
- https://kotlinlang.org/docs/coding-conventions.html#class-layout
- 불필요한 코드 및 주석 샂게
- import * 제거
- 메서드명 수정
- Spring Data Mongo Query Method & `@Query` 수정
- 충돌난 코드가 꽤나 많아서 직접 수정하긴 했지만 혹시 실수로 제거한 부분이 존재할 수 있습니다.
- 리마인드 로직이 사용되는 곳은 대부분 수정하여 사이드 이펙트가 꽤 존재할 수 있습니다..😭
- 리마인드 발송 로직은 아직 완벽히 수정한게 아니라 해당 PR 올린 후 수정하여 Update 하려고 합니다.
- 테스트가 깨지는게 꽤나 많을 것 같은데.. 부채 하나씩 갚아가보죵...😭

[#140] 리마인드 로직 수정 및 리팩터링

---

src/main/kotlin/com/yapp/web2/batch/job/JobCompletionListener.kt
src/main/kotlin/com/yapp/web2/batch/job/NotificationJob.kt
src/main/kotlin/com/yapp/web2/batch/job/TrashRefreshJob.kt
src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/controller/BookmarkInterfaceController.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/entity/Remind.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/repository/BookmarkRepository.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt
src/main/kotlin/com/yapp/web2/infra/fcm/FirebaseService.kt
src/main/kotlin/com/yapp/web2/infra/slack/SlackService.kt
src/main/kotlin/com/yapp/web2/infra/slack/SlackServiceImpl.kt

- 북마크 내 리마인드가 리스트로 구조가 변경됨에 따라 관련 로직 수정
- 리마인드 관련 로직 수정
- 로깅 추가
- 슬랙 알림 추가
- 예외 처리

[#140] 리마인드 관련 리팩토링

---

src/main/kotlin/com/yapp/web2/domain/account/service/AccountService.kt
src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt

- 리마인드 주기 설정 API 이슈 수정 및 알림 메시지 변경
- 리마인드 주기 설정 API 이슈 수정 및 알림 메시지 변경

리마인드 주기 설정 API 이슈 수정 및 알림 메시지 변경

---

src/main/kotlin/com/yapp/web2/domain/remind/service/RemindService.kt

- 리마인드 발송 실패 시 슬랙 및 로깅에 에러 메시지 추가

[#185] 리마인드 발송 실패 시 슬랙, 로깅 메시지 추가

---

src/main/kotlin/com/yapp/web2/BookmarkersApplication.kt
src/main/kotlin/com/yapp/web2/domain/bookmark/BookmarkDto.kt
src/test/kotlin/com/yapp/web2/domain/bookmark/service/SharedBookmarkServiceTest.kt

Job과 main문에서 중복으로 사용되었던 EnableBatchProcess 어노테이션을 제거함

[#25] fix(slack alarm)
